server:
  port: 8081  servlet:    context-path: /im
  #address: 172.3.21.211
spring:  datasource:    url: jdbc:mysql://localhost:3306/imdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:    pathmatch:      use-suffix-pattern: true #true表示后缀可加任何东西。false表示不能加后缀      use-registered-suffix-pattern: false
        view:      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
mybatis:  mapper-locations: classpath:mapper/*.xml  type-aliases-package: "com.im.pojo"